# Generated by Django 6.0.6 on 2026-06-04 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('emplacement', models.CharField(max_length=100, verbose_name='Emplacement')),
                ('stock_reel', models.PositiveIntegerField(default=0, verbose_name='Stock réel')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('stock_minimum', models.PositiveIntegerField(default=0, verbose_name='Stock minimum')),
                ('stock_maximum', models.PositiveIntegerField(default=100, verbose_name='Stock maximum')),
                ('type_piece', models.CharField(choices=[('mecanique', 'Mécanique'), ('pneumatique', 'Pneumatique'), ('electrique', 'Électrique')], default='mecanique', max_length=20, verbose_name='Type de pièce')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('consommation', 'Consommation'), ('reception', 'Réception')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('stock_avant', models.PositiveIntegerField()),
                ('stock_apres', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='pieces.piece')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'ordering': ['-date'],
            },
        ),
    ]
