# Generated by Django 6.0.5 on 2026-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pieces/', verbose_name='Photo'),
        ),
    ]
