# Generated by Django 6.0.5 on 2026-06-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='criticite',
            field=models.BooleanField(default=False, verbose_name='Pièce critique'),
        ),
    ]
