# Generated by Django 6.0.5 on 2026-06-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0004_piece_criticite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matricule technicien'),
        ),
    ]
