# Generated by Django 6.0.5 on 2026-06-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0005_mouvementstock_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='type_piece',
            field=models.CharField(choices=[('mecanique', 'Mécanique'), ('pneumatique', 'Pneumatique'), ('electrique', 'Électrique'), ('autre', 'Autre')], default='mecanique', max_length=20, verbose_name='Type de pièce'),
        ),
    ]
