# Generated by Django 6.0.5 on 2026-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0006_alter_piece_type_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Code'),
        ),
    ]
