# Generated by Django 6.0.5 on 2026-05-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('mode', models.CharField(choices=[('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque')], max_length=50)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('impaye', 'Impayé')], default='en_attente', max_length=20)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat')),
            ],
        ),
    ]
