# Generated by Django 6.0.5 on 2026-05-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('type_societe', models.CharField(choices=[('SARL', 'SARL'), ('SAS', 'SAS'), ('Auto-entrepreneur', 'Auto-entrepreneur'), ('Autre', 'Autre')], max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
