# Generated by Django 6.0.5 on 2026-05-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('pack', models.CharField(choices=[('standard', 'Standard - 3000 DH'), ('premium', 'Premium - 3900 DH'), ('premium_plus', 'Premium+ - 4990 DH'), ('domiciliation', 'Domiciliation seule - 2000 DH')], max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('resilie', 'Résilié'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('adresse_domiciliation', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
